src/Entity/JobOffer.php
<?php

namespace App\Entity;

use App\Repository\JobOfferRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: JobOfferRepository::class)]
class JobOffer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Client::class, inversedBy: 'jobOffers')]
    #[ORM\JoinColumn(name: 'client_id', referencedColumnName: 'id', nullable: false, onDelete: 'CASCADE')]
    private ?Client $client = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?bool $activity = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $notes = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column(length: 255)]
    private ?string $location = null;

    #[ORM\ManyToOne(inversedBy: 'jobOffers')]
    private ?JobCategory $job_category = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $closing_date = null;

    #[ORM\Column]
    private ?int $salary = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $creation_date = null;

    #[ORM\OneToMany(mappedBy: 'job_offer', targetEntity: Application::class)]
    private Collection $applications;


    public function __construct()
    {
        $this->applications = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function isActivity(): ?bool
    {
        return $this->activity;
    }

    public function setActivity(bool $activity): self
    {
        $this->activity = $activity;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): self
    {
        $this->notes = $notes;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getJobCategory(): ?JobCategory
    {
        return $this->job_category;
    }

    public function setJobCategory(?JobCategory $job_category): self
    {
        $this->job_category = $job_category;

        return $this;
    }

    public function getClosingDate(): ?\DateTimeInterface
    {
        return $this->closing_date;
    }

    public function setClosingDate(\DateTimeInterface $closing_date): self
    {
        $this->closing_date = $closing_date;

        return $this;
    }

    public function getSalary(): ?int
    {
        return $this->salary;
    }

    public function setSalary(int $salary): self
    {
        $this->salary = $salary;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    /**
     * @return Collection<int, Application>
     */
    public function getApplications(): Collection
    {
        return $this->applications;
    }

    public function addApplication(Application $application): self
    {
        if (!$this->applications->contains($application)) {
            $this->applications->add($application);
            $application->setJobOffer($this);
        }

        return $this;
    }

    public function removeApplication(Application $application): self
    {
        if ($this->applications->removeElement($application)) {
            // set the owning side to null (unless already changed)
            if ($application->getJobOffer() === $this) {
                $application->setJobOffer(null);
            }
        }

        return $this;
    }

    
}

src/Form/JobOfferType.php
<?php

namespace App\Form;

use App\Entity\Client;
use App\Entity\JobOffer;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;

class JobOfferType extends AbstractType
{
    private $entityManager;
    
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $clients= $this->entityManager->getRepository(Client::class)->findAll();
        
        
        $builder
            ->add('title')
            ->add('type', ChoiceType::class, [
                'choices' => [
                    'Full Time' => 'full_time',
                    'Part Time' => 'part_time',
                    'Temporary' => 'temporary',
                    'Freelance' => 'freelance',
                    'Seasonal'  => 'seasonal',
                ],
                'attr' => [
                    'class' => 'mdb-select md-form colorful-select dropdown-primary',
                    'id' => 'type'
                ],
                'label' => 'Type',
                'required' => true,
            ])
            ->add('activity', ChoiceType::class, [
                'expanded' => true,
                'multiple' => false,
                'choices' => [
                    'Yes' => true,
                    'No' => false,
                ],
            ])
            // ->add('client_id', EntityType::class, [
            //     'class' => Client::class,
            //     'choice_label' => 'society_name',
            //     'placeholder' => 'Choose a client',
            //     'required' => true,
            // ])
            // ->add('job_category')
            ->add('description')
            ->add('location')
            ->add('salary')
            ->add('closing_date', DateTimeType::class, [
                'widget' => 'single_text',
                'html5' => false,
                'attr' => ['class' => 'js-datetimepicker'],
                // Format de date à utiliser
                'format' => 'yyyy-MM-dd HH:mm',
                'label' => 'Closing Date' //Ajout du label pour le champ
            ])
            ->add('notes')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => JobOffer::class,
        ]);
    }
}

src/Controller/JobOfferController.php
<?php

namespace App\Controller;

use App\Entity\JobOffer;
use App\Entity\Application;
use App\Form\JobOfferType;
use App\Form\EntityType;
use App\Repository\JobOfferRepository;
use App\Repository\JobCategoryRepository;
use App\Repository\ClientRepository;
use App\Repository\ApplicationRepository;
use App\Repository\CandidateRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManager;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

#[Route('/job/offer')]
class JobOfferController extends AbstractController
{
	// private JobOffer $jobOffer;
	// private JobOfferRepository $jobOfferRepository;
	// private Request $request;

    // public function __construct(JobOffer $jobOffer, JobOfferRepository $jobOfferRepository, Request $request) {
    //     $this->jobOffer = $jobOffer;
    //     $this->jobOfferRepository = $jobOfferRepository;
    //     $this->request = $request;
    // }

    #[Route('/', name: 'app_job_offer_index', methods: ['GET'])]
    public function index(JobOfferRepository $jobOfferRepository): Response
    {

        return $this->render('job_offer/index.html.twig', [
            'job_offers' => $jobOfferRepository->findBy([], ['creation_date' => 'DESC']),
        ]);
    }

    #[Route('/edit/{id<\d+>?}', name: 'app_job_offer_edit', methods: ['GET', 'POST'])]
    public function edit(?int $id, JobOfferRepository $jobOfferRepository, Request $request, JobCategoryRepository $jobCategoryRepository, EntityManagerInterface $entityManager, ClientRepository $clientRepository): Response
    {
        if ($id !== null) {
            $jobOffer = $jobOfferRepository->findOneBy(['id' => $id]);
        } else {
			$jobOffer = new JobOffer();
            $jobOffer->setCreationDate(new \DateTimeImmutable(date('Y-m-d H:i:s')));
		}
     
  
        //Get All
        $jobCategories = $jobCategoryRepository->findAll();
        $clients = $clientRepository->findAll();

        $data = $request->request->all();

        if (count($data) > 0) {
            $jobOffer->setClient($clientRepository->findOneBy(['id' => $data['client_id']]))
					->setJobCategory($jobCategoryRepository->findOneBy(['id' => $data['job_category_id']]))
					->setDescription($data['description'])
					->setActivity($data['activity'])
					->setNotes($data['notes'])
					->setTitle($data['title'])
					->setType($data['type'])
					->setLocation($data['location'])
					->setSalary($data['salary'])
					->setClosingDate(new \DateTimeImmutable($data['closing_date']))
					;
    
            $entityManager->persist($jobOffer);
            $entityManager->flush();

			return $this->redirectToRoute('app_job_offer_edit', ['id' => $jobOffer->getId()]);
        }



        return $this->render('job_offer/edit.html.twig', [
            'job_offer' => $jobOffer,
            'job_categories' => $jobCategories,
			'clients' => $clients,
        ]);
    }

    #[Route('/{id}', name: 'app_job_offer_show', methods: ['GET'])]
    public function show(JobOffer $jobOffer, ApplicationRepository $applicationRepository, EntityManagerInterface $entityManager, TokenStorageInterface $tokenStorage, CandidateRepository $candidateRepository, JobOfferRepository $jobOfferRepository): Response
    {

        $applications = $applicationRepository->findBy(['job_offer' => $jobOffer->getId()]);
        

        // Constants for the Apply_button
        $allreadyApply=0;
        $candidate = null;

        if ($tokenStorage->getToken()){            
            $user = $tokenStorage->getToken()->getUser();
            $candidates = $candidateRepository->findBy(['user' => $user->getId()]);
            $candidate = $candidates[0];
    
            foreach($applications as $application){
                if ($application->getCandidateId()->getId() == $candidate->getId()){
                    $allreadyApply+=1;
                };
            }
        }

        // Constants for the Previous/Next_buttons
        $queryBuilder = $jobOfferRepository->createQueryBuilder('e')
            ->select('e')
            ->orderBy('e.id', 'ASC');
        $query = $queryBuilder->getQuery();

        $entities = $query->getResult();
        $nextEntity = null;
        $previousEntity = null;
        foreach ($entities as $index => $currentEntity) {
            if ($currentEntity->getId() == $jobOffer->getId()) {
                $nextEntity = $entities[$index + 1] ?? null;
                if ($index > 0) {
                    $previousEntity = $entities[$index - 1];
                }
                break;
            }
        }

        

        // dd($previousEntity, $nextEntity);

        return $this->render('job_offer/show.html.twig', [
            'job' => $jobOffer,
            'candidate' => $candidate,
            'allreadyApply' => $allreadyApply,
            'previousEntity' => $previousEntity,
            'nextEntity' => $nextEntity,
        ]);
    }

    #[Route('/registration/{id}', name: 'app_job_offer_applicationRegister', methods: ['GET'])]
    public function applicationRegister(JobOffer $jobOffer, ApplicationRepository $applicationRepository, EntityManagerInterface $entityManager, TokenStorageInterface $tokenStorage, CandidateRepository $candidateRepository): Response
    {
        $user = $tokenStorage->getToken()->getUser();
        $candidate = $candidateRepository->findBy(['user' => $user->getId()]);

        $application = new Application($jobOffer, $candidate[0]);
        $application->setCreatedAt(new \DateTimeImmutable(date('Y-m-d H:i:s')));
        $entityManager->persist($application);
        $entityManager->flush();

        // $applications = $applicationRepository->findBy(['job_offer' => $jobOffer->getId()]);

        // return $this->render('job_offer/show.html.twig', [
        //     'job' => $jobOffer,
        //     'applications' => $applications,
        // ]);

        return $this->redirectToRoute('app_job_offer_show', [
            'id' => $jobOffer->getId()
        ]);
    }

    #[Route('/{id}', name: 'app_job_offer_delete', methods: ['POST'])]
    public function delete(Request $request, JobOffer $jobOffer, JobOfferRepository $jobOfferRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$jobOffer->getId(), $request->request->get('_token'))) {
            $jobOfferRepository->remove($jobOffer, true);
        }

        return $this->redirectToRoute('app_admin_job_offer_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/job_offer/_delete_form.html.twig
<form method="post" action="{{ path('app_job_offer_delete', {'id': job_offer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ job_offer.id) }}">
    <button class="btn">Delete</button>
</form>

templates/job_offer/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/job_offer/edit.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}New JobOffer{% endblock %}

{% block body %}
<div style="height:100px"></div>
<h1>{{ job_offer.id ? 'Update' : 'Create new' }} JobOffer</h1>

<form action="#" method="post">
	<input type="hidden" name="_token" value="">

	<div class="input-field">
		<input type="text" name="title" value="{{ job_offer.getTitle() ? job_offer.getTitle() : '' }}">
		<label for="title">Title</label>
		<span class="help-block">Insert the title of the offer</span>
	</div>

	<div class="">
        <label for="type">Type</label>
		<select name="type" id="type">
			<option value="" {{ job_offer.type ? '' : 'selected' }}>Choose an option</option>
			<option value="full_time" {{ job_offer.type == "full_time" ? 'selected' : '' }}>Full Time</option>
			<option value="part_time" {{ job_offer.type == "part_time" ? 'selected' : '' }}>Part Time</option>
			<option value="temporary" {{ job_offer.type == "temporary" ? 'selected' : '' }}>Temporary</option>
			<option value="freelance" {{ job_offer.type == "freelance" ? 'selected' : '' }}>Freelance</option>
			<option value="seasonal" {{ job_offer.type == "seasonal" ? 'selected' : '' }}>Seasonal</option>
		</select>
	</div>

	<div class="">
        <label for="client_id">Client</label>
		<select name="client_id" id="client_id">
			<option value="" {{ job_offer.client() ? job_offer.client().id ? '' : 'selected' : ''}}>Choose an option</option>
			{% for client in clients %}
			<option value="{{client.id}}" {{ job_offer.client() ? job_offer.client().id == client.id ? 'selected' : '' : ''}}>{{ client.getSocietyName() }}</option>
            {% endfor %}
		</select>
	</div>

	<div class="">
        <label for="job_category_id">Job Category</label>
		<select name="job_category_id" id="job_category_id">
			<option value="" {{ job_offer.getJobCategory() ? job_offer.getJobCategory().id ? '' : 'selected' : ''}}>Choose an option</option>
			{% for category in job_categories %}
			<option value="{{category.id}}" {{ job_offer.getJobCategory() ? job_offer.getJobCategory().id == category.id ? 'selected' : '' : ''}}>{{ category.getName() }}</option>
            {% endfor %}
		</select>
	</div>

	<div class="input-field">
		<textarea class="materialize-textarea" name="description" id="description" cols="50" rows="10" value="{{ job_offer.getDescription() ? job_offer.getDescription() : '' }}">{{ job_offer.getDescription() ? job_offer.getDescription() : '' }}</textarea>
		<label for="description">Description</label>
		<span class="help-block">Description of the offer</span>
	</div>

	<div class="input-field">
		<input type="text" name="location" value="{{ job_offer.getLocation() ? job_offer.getLocation() : '' }}">
		<label for="location">Location</label>
		<span class="help-block">Insert the location of the offer</span>
	</div>

	<div class="input-field">
		<input type="number" name="salary" value="{{ job_offer.getSalary() ? job_offer.getSalary() : '' }}">
		<label for="salary">Salary</label>
		<span class="help-block">Insert the salary of the offer</span>
	</div>

	<div class="input-field">
		<input type="date" name="closing_date" value="{{ job_offer.getClosingDate() ? job_offer.getClosingDate().format('Y-m-d') : '' }}">
		<label for="closing_date">Closing Date</label>
		<span class="help-block">Insert the closing date of the offer</span>
	</div>

	<div class="input-field">
		<textarea class="materialize-textarea" name="notes" id="notes" cols="50" rows="10" value="{{ job_offer.getNotes() ? job_offer.getNotes() : '' }}">{{ job_offer.getNotes() ? job_offer.getNotes() : '' }}</textarea>
		<label for="notes">Notes</label>
		<span class="help-block">Notes about the offer</span>
	</div>

	<div class="input-field">
		<legend>Is the offer still active ?</legend>

		<div>
			<input type="radio" id="1" name="activity" value="1"
						 checked>
			<label for="1">Yes</label>
		</div>

		<div>
			<input type="radio" id="0" name="activity" value="0">
			<label for="0">No</label>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12 col-sm-6 col-md-4 col-md-offset-4">
			<button type="submit" class="btn btn-block btn-lg gradient secondary waves-effect waves-light">
				<span><strong>{{ job_offer.id ? 'UPDATE' : 'SAVE' }}</strong> NOW</span>
			</button>
		</div>
</div>
</form>

<a href="{{ path('app_job_offer_index') }}">back to list</a>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('select');
        var instances = M.FormSelect.init(elems);
      });
</script>
{% endblock %}

templates/job_offer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Luxury Offers{% endblock %}

{% block body %}

<div class="base">

	<!-- Page -->
	<div class="page">

		<!-- Page Header-->
		<section class="page-title page-title-bg fixed-bg overlay dark-5 padding-top-160 padding-bottom-80">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h2 class="white-text">Our job offers</h2>
						<span class="white-text">Search and filter by job category</span>

					</div>
				</div>
			</div>
		</section>

		<!-- Page Content-->
		<section id="job-offers" class="section-padding gray-bg">
			<div class="container">
				<div class="text-center mb-40">
					<h2 class="section-title">We have the perfect job for you</h2>
					<p class="section-sub">just like our candidates, we offer quality, serious & reliable job offers.</p>
				</div>
				<div class="portfolio-container">

					<ul class="portfolio-filter brand-filter text-center">
						<li class="active waves-effect waves-light" data-group="all">All</li>
						<li class=" waves-effect waves-light" data-group="Commercial">Commercial</li>
						<li class=" waves-effect waves-light" data-group="Retail sales">Retail sales</li>
						<li class=" waves-effect waves-light" data-group="Creative">Creative</li>
						<li class=" waves-effect waves-light" data-group="Technology">Technology</li>
						<li class=" waves-effect waves-light" data-group="Marketing & PR">Marketing & PR</li>
						<li class=" waves-effect waves-light" data-group="Fashion & luxury">Fashion & luxury</li>
						<li class=" waves-effect waves-light" data-group="Management & HR">Management & HR</li>
					</ul>
					<div class="portfolio portfolio-with-title col-2 gutter mt-30">
						{% for job in job_offers %}
						<div class="portfolio-item" data-groups='["{{job.jobCategory.name}}"]'>
							<div class="portfolio-wrapper">
								<div class="card job-card">
									<div class="card-content">
										<span class="title">
											<span class="card-title">{{ job.title }}</span>
											<span class="ref grey-text">Ref. AA{{ job.id }}</span>
										</span>
										<div class="metas mb-20">
											<div class="meta">
												<i class="material-icons">&#xE53E;</i>{{ job.salary }}&euro;
											</div>
											<div class="meta">
												<i class="material-icons">&#xE916;</i>{{ job.closingDate|date('Y-m-d') }}
											</div>
											<div class="meta">
												<i class="material-icons">&#xE55F;</i>{{ job.location }}
											</div>
										</div>
										<p class="truncate-text">{{ job.description }}</p>
									</div>
									<div class="card-action">
										<a class="btn btn-md primary border waves-effect waves-dark" href="{{ path('app_job_offer_show', {'id': job.id}) }}">Details</a>
										{# <a class="btn btn-md primary waves-effect waves-light" href="#!">Apply</a> #}
									</div>
								</div>
							</div>
						</div>
						{% endfor %}


						<div class="no-item"></div>
					</div>
				</div>
			</div>
		</section>

		<section class="cta-candidate bg-fixed bg-cover overlay dark-5 padding-top-70 padding-bottom-50">
			<div class="container">
				<div class="row">
					<div class="valign-wrapper text-center">
						<div class="hero-intro valign-cell">
							<h2 class="tt-headline clip is-full-width no-margin">
								<span>You are </span>
								<span class="tt-words-wrapper">
									<b class="is-visible">Commercial</b>
									<b>Creative</b>
									<b>Marketing & PR</b>
									<b>Technology</b>
									<b>Fashion & luxury</b>
									<b>Retail sales</b>
								</span>
							</h2>
							<h3 class="c-secondary mb-30 no-margin">Sign-up and apply for jobs now</h3>
							<p class="white-text section-sub">Each one of your skills is seen as precious resource to us, each one of
								your personality traits are considered as an added on value. Joining us is allowing our recruitment
								expertise and personal guidance to bring the best out in you by choosing the most suited position.</p>

							<a href="/register.html" class="btn border secondary waves-effect waves-light mt-40">Join us</a>
						</div>
					</div>
				</div>
			</div>
		</section>

	</div>

</div>

{% block js %}
<script type="text/javascript">

	onAppReady(function () {
		$('.preload').remove();
	});
</script>
{% endblock %}

{% endblock %}

templates/job_offer/new.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}New JobOffer{% endblock %}

{% block body %}
<div style="height:100px"></div>
<h1>{{ job_offer.id ? 'Update' : 'Create new' }} JobOffer</h1>

<form action="#" method="post">
	<input type="hidden" name="_token" value="">

	<div class="input-field">
		<input type="text" name="title" value="{{ job_offer.getTitle() ? job_offer.getTitle() : '' }}">
		<label for="title">Title</label>
		<span class="help-block">Insert the title of the offer</span>
	</div>

	<div class="input-field">
		<select name="type" id="type">
			<option value="full_time">Full Time</option>
			<option value="part_time">Part Time</option>
			<option value="temporary">Temporary</option>
			<option value="freelance">Freelance</option>
			<option value="seasonal">Seasonal</option>
		</select>
		<label for="type">Type</label>
		<span class="help-block">Insert the type of the offer</span>
	</div>

	<div class="row">
		<div class="col-xs-12 col-sm-6 col-md-4 col-md-offset-4">
			<button type="submit" class="btn btn-block btn-lg gradient secondary waves-effect waves-light">
				<span><strong>{{ job_offer.id ? 'UPDATE' : 'SAVE' }}</strong> NOW</span>
			</button>
		</div>
</div>
</form>

<a href="{{ path('app_job_offer_index') }}">back to list</a>
{% endblock %}

templates/job_offer/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Luxury Offer{% endblock %}

{% block body %}

<div class="base">

    <!-- Page -->
    <div class="page">

        <!-- Page Header-->
        <section class="page-title page-title-bg fixed-bg overlay dark-5 padding-top-160 padding-bottom-80">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="white-text">{{job.title}}</h2>
                        <span class="white-text">Ref. AA{{ job.id }}</span>
                        <ol class="breadcrumb">
                            <li>
                                <div class="portfolio-nav">
                                    <a href="#!" class="waves-effect waves-dark"><i class="fa fa-angle-left" aria-hidden="true"></i> Prev</a>
                                    <a href="#!" class="waves-effect waves-dark"><i class="fa fa-th-large" aria-hidden="true"></i></a>
                                    <a href="#!" class="waves-effect waves-dark">Next <i class="fa fa-angle-right" aria-hidden="true"></i></a>
                                </div>
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>

        <!-- Page Content-->
        <section class="single-project-section section-padding light-gray-bg">
            <div class="container">
                <div class="project-overview">
                    <div class="row mb-80">
                        <div class="col-xs-12 col-md-8">
                            <p class="ref grey-text no-margin">Ref. AA{{ job.id }}</p>
                            <h2>{{ job.title }}</h2>
                            <p>{{ job.description }}</p>
                        </div>

                        <div class="col-xs-12 col-md-4 quick-overview">
                            <ul class="portfolio-meta">
                                <li><span> Pulished at </span>{{ job.creationDate|date('d M y') }}</li>
                                <li><span> Position </span>{{job.jobCategory.name}}</li>
                                <li><span> Contract Type </span>{{job.type}}</li>
                                <li><span> Salary </span>{{job.salary}} &euro;</li>
                                <li><span> Location </span>{{job.location}}</li>
                                <li><span> Starting date </span>2018-05-18</li>
                            </ul>
                            {% if allreadyApply < 1 %}
                                {% if candidate %} 
                                    {% if candidate.completeProfile %} 
                                    <a class='btn btn-block gradient primary mt-30 waves-effect waves-light' href='{{ path('app_job_offer_applicationRegister', {'id': job.id}) }}'>Apply for this job</a>
                                    {% else %}
                                    <a class='btn btn-block gradient red mt-30 waves-effect waves-light' href='{{ path('app_candidate_new', {'id': app.user.id}) }}'>Complete your profile to apply</a>
                                    {% endif %}
                                {% endif %}
                            {% else %}
                                <div class="btn btn-block btn-success mt-30 waves-effect waves-light disabled">You have applied for this job</div>
                            {% endif %}
                            
                            
                        </div>
                    </div>
                </div>

                <nav class="single-post-navigation no-margin" role="navigation">
                    <div class="row">

                        {% if previousEntity %}
                        <div class="col-xs-6 col-sm-6 col-md-4">
                            <div class="previous-post-link">
                                <a class="btn border primary waves-effect waves-dark" href="{{ path('app_job_offer_show', {'id': previousEntity.id}) }}">
                                    <i class="fa fa-long-arrow-left"></i>Previous
                                </a>
                            </div>
                        </div>
                        <div class="hidden-xs hidden-sm col-md-4"></div>
                        {% endif %}

                        {% if nextEntity %}
                        <div class="col-xs-6 col-sm-6 col-md-4">
                            <div class="next-post-link">
                                <a class="btn border primary waves-effect waves-dark" href="{{ path('app_job_offer_show', {'id': nextEntity.id}) }}">
                                    Next <i class="fa fa-long-arrow-right"></i>
                                </a>
                            </div>
                        </div>
                        {% endif %}

                    </div>
                </nav>
            </div>
        </section>

    </div>

</div>

	{% block js %}
	<script type="text/javascript">

		onAppReady(function () {
			$('.preload').remove();
		});
	</script>
	{% endblock %}

{% endblock %}