src/Entity/Candidate.php
<?php

namespace App\Entity;

use App\Repository\CandidateRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CandidateRepository::class)]
class Candidate
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $gender = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $country = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nationality = null;

    #[ORM\Column(nullable: true)]
    private ?bool $passport = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $passport_file = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $cv = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $profile_picture = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $current_location = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $birthdate = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $birth_location = null;

    #[ORM\Column(nullable: true)]
    private ?bool $availability = null;

    #[ORM\ManyToOne(inversedBy: 'candidates')]
    private ?JobCategory $job_category_id = null;

    #[ORM\ManyToOne(inversedBy: 'candidates', cascade: ['persist', 'remove'])]
    private ?User $user = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $experience = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $short_description = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $deleted_at = null;

    #[ORM\Column(nullable: true)]
    private ?bool $deleted = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $files = null;

    #[ORM\OneToMany(mappedBy: 'candidate_id', targetEntity: Application::class)]
    private Collection $applications;

    #[ORM\Column(nullable: true)]
    private ?bool $completeProfile = null;

    public function __construct()
    {
        $this->applications = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(?string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getNationality(): ?string
    {
        return $this->nationality;
    }

    public function setNationality(?string $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }

    public function isPassport(): ?bool
    {
        return $this->passport;
    }

    public function setPassport(?bool $passport): self
    {
        $this->passport = $passport;

        return $this;
    }

    public function getPassportFile(): ?string
    {
        return $this->passport_file;
    }

    public function setPassportFile(?string $passport_file): self
    {
        $this->passport_file = $passport_file;

        return $this;
    }

    public function getCv(): ?string
    {
        return $this->cv;
    }

    public function setCv(?string $cv): self
    {
        $this->cv = $cv;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profile_picture;
    }

    public function setProfilePicture(?string $profile_picture): self
    {
        $this->profile_picture = $profile_picture;

        return $this;
    }

    public function getCurrentLocation(): ?string
    {
        return $this->current_location;
    }

    public function setCurrentLocation(?string $current_location): self
    {
        $this->current_location = $current_location;

        return $this;
    }

    public function getBirthdate(): ?\DateTimeInterface
    {
        return $this->birthdate;
    }

    public function setBirthdate(?\DateTimeInterface $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getBirthLocation(): ?string
    {
        return $this->birth_location;
    }

    public function setBirthLocation(?string $birth_location): self
    {
        $this->birth_location = $birth_location;

        return $this;
    }

    public function isAvailability(): ?bool
    {
        return $this->availability;
    }

    public function setAvailability(?bool $availability): self
    {
        $this->availability = $availability;

        return $this;
    }

    public function getJobCategoryId(): ?JobCategory
    {
        return $this->job_category_id;
    }

    public function setJobCategoryId(?JobCategory $job_category_id): self
    {
        $this->job_category_id = $job_category_id;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getExperience(): ?string
    {
        return $this->experience;
    }

    public function setExperience(?string $experience): self
    {
        $this->experience = $experience;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(?string $short_description): self
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
    if (!$this->created_at) {
        $this->setCreatedAt(new \DateTimeImmutable(date('Y-m-d H:i:s')));
    }

    return $this->created_at;
}

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeImmutable
    {
        return $this->deleted_at;
    }

    public function setDeletedAt(?\DateTimeImmutable $deleted_at): self
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    public function isDeleted(): ?bool
    {
        return $this->deleted;
    }

    public function setDeleted(?bool $deleted): self
    {
        $this->deleted = $deleted;

        return $this;
    }

    public function getFiles(): ?string
    {
        return $this->files;
    }

    public function setFiles(?string $files): self
    {
        $this->files = $files;

        return $this;
    }

    /**
     * @return Collection<int, Application>
     */
    public function getApplications(): Collection
    {
        return $this->applications;
    }

    public function addApplication(Application $application): self
    {
        if (!$this->applications->contains($application)) {
            $this->applications->add($application);
            $application->setCandidateId($this);
        }

        return $this;
    }

    public function removeApplication(Application $application): self
    {
        if ($this->applications->removeElement($application)) {
            // set the owning side to null (unless already changed)
            if ($application->getCandidateId() === $this) {
                $application->setCandidateId(null);
            }
        }

        return $this;
    }

    public function getCompleteProfile(): ?bool
    {
        return $this->completeProfile;
    }

    public function setCompleteProfile(?bool $completeProfile): self
    {
        $this->completeProfile = $completeProfile;

        return $this;
    }

    
    
}

src/Controller/CandidateController.php
<?php

namespace App\Controller;

use App\Entity\Candidate;
use App\Entity\User;
use App\Entity\JobCategory;
use App\Form\CandidateType;
use App\Repository\CandidateRepository;
use App\Repository\JobCategoryRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Annotation\UploadedFile;

#[Route('/candidate')]
class CandidateController extends AbstractController
{

    #[Route('/', name: 'app_candidate_index', methods: ['GET'])]
    public function index(CandidateRepository $candidateRepository): Response
    {
        return $this->render('candidate/index.html.twig', [
            'candidates' => $candidateRepository->findBy([], ['created_at' => 'DESC']),
        ]);
    }

    #[Route('/new/{id}', name: 'app_candidate_new', methods: ['GET', 'POST'])]
    public function new(User $user, Request $request, CandidateRepository $candidateRepository, EntityManagerInterface $entityManager, JobCategoryRepository $jobCategoryRepository): Response
    {
        //Get All job_category
        $jobCategories = $entityManager->getRepository(JobCategory::class)->findAll();

        // Get the existing candidate for the user, if it exists
        $candidate = $candidateRepository->findOneBy(['user' => $user]);

        // If the candidate doesn't exist, create a new one
        if (!$candidate) {
            $candidate = new Candidate();
        }

        if (!$candidate->getCreatedAt()) {
            $candidate->setCreatedAt(new \DateTimeImmutable(date('Y-m-d H:i:s')));
        }

        $candidate->setUser($user);

        if ($request->files) {
            $passportFile = $request->files->get('passport');
            $cvFile = $request->files->get('cv');
            $photoFile = $request->files->get('photo');
            
            if ($photoFile) {
                $newPhotoFile = sprintf('user_%d_photo.%s', $user->getId(), $photoFile->guessExtension());
                $destinationPath = '../public/assets/img/photo/' . $newPhotoFile; 

                try {
                    $photoFile->move($destinationPath, $newPhotoFile);
                    $candidate->setProfilePicture($newPhotoFile);
                    // dd($candidate);
                } catch (FileException $e) {
                    echo $e->getMessage();
                }

            }
            
            if ($cvFile) {
                $newCvFile = sprintf('user_%d_cv.%s', $user->getId(), $cvFile->guessExtension());
                $destinationPath = '../public/assets/img/cv/' . $newCvFile; 

                try {
                    $cvFile->move($destinationPath, $newCvFile);
                    $candidate->setCv($newCvFile);
                } catch (FileException $e) {
                    echo $e->getMessage();
                }
            }
            
            if ($passportFile) {
                $newPassportFile = sprintf('user_%d_passport.%s', $user->getId(), $passportFile->guessExtension());
                $destinationPath = '../public/assets/img/passport/' . $newPassportFile; 

                try {
                    $passportFile->move($destinationPath, $newPassportFile);
                    $candidate->setPassportFile($newPassportFile);
                    $candidate->setPassport(true);
                } catch (FileException $e) {
                    echo $e->getMessage();
                }
            }
        }

        // dd($request->files, $candidate);


        if ($request->request->count() > 0) {
            $candidate->setFirstname($request->request->get('first_name'));
            $candidate->setLastname($request->request->get('last_name'));
            $candidate->setGender($request->request->get('gender'));
            $candidate->setCurrentLocation($request->request->get('current_location'));
            $candidate->setAddress($request->request->get('address'));
            $candidate->setCountry($request->request->get('country'));
            $candidate->setNationality($request->request->get('nationality'));
            $candidate->setBirthLocation($request->request->get('birth_place'));
            $candidate->setShortDescription($request->request->get('description'));
            $candidate->setExperience($request->request->get('experience'));
            $candidate->setAvailability($request->request->get('availability'));
            $candidate->setjobCategoryId($jobCategoryRepository->findOneBy(['id' => $request->request->get('job_sector')]));
            $candidate->setUpdatedAt(new \DateTimeImmutable(date('Y-m-d H:i:s')));
            $dateString = $request->request->get('birth_date');
            if ($dateString) {
                $birthdate = new \DateTimeImmutable($dateString);
                $candidate->setBirthdate($birthdate);
            }
        }

        // dd($candidate);

        $entityManager->persist($candidate);
        $entityManager->flush();


        // Counting the number of columns in the Candidates table
        $metadata = $entityManager->getClassMetadata(Candidate::class);
        $columnCount = count($metadata->getColumnNames());

        // Counting the number of currently filled columns
        $reflectionClass = new \ReflectionClass($candidate);
        $nonNullCount = 1;
        foreach ($reflectionClass->getProperties() as $property) {
            $property->setAccessible(true);
            if ($property->getValue($candidate) !== null && $property->getValue($candidate) !== '') {
                $nonNullCount++;
            }
        }

        // Calculating the percent of fullfill
        $percentage = ($nonNullCount / $columnCount) * 100;

        if ($percentage >= 100){
            $percentage = 100;
            $candidate->setCompleteProfile(true);

            $entityManager->persist($candidate);
            $entityManager->flush();
        }


        return $this->render('candidate/new.html.twig', [
            'candidate' => $candidate,
            'job_categories' => $jobCategories,
            'percentage' => $percentage,
        ]);
    }

    #[Route('/show/{id}', name: 'app_candidate_show', methods: ['GET'])]
    public function show(User $user, CandidateRepository $candidateRepository): Response
    {
        $candidate = $candidateRepository->findOneBy(['user' => $user]);

        return $this->render('candidate/show.html.twig', [
            'candidate' => $candidate,
        ]);
    }

    #[Route('/edit/{id}', name: 'app_candidate_edit', methods: ['GET', 'POST'])]
    public function edit(Candidate $candidate, Request $request, CandidateRepository $candidateRepository): Response
    {
        $form = $this->createForm(CandidateType::class, $candidate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $candidateRepository->save($candidate, true);

            return $this->redirectToRoute('app_candidate_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('candidate/edit.html.twig', [
            'candidate' => $candidate,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_candidate_delete', methods: ['POST'])]
    public function delete(Request $request, Candidate $candidate, CandidateRepository $candidateRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$candidate->getId(), $request->request->get('_token'))) {
            $candidateRepository->remove($candidate, true);
        }

        return $this->redirectToRoute('app_candidate_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/candidate/_delete_form.html.twig
<form method="post" action="{{ path('app_candidate_delete', {'id': candidate.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ candidate.id) }}">
    <button class="btn">Delete</button>
</form>

templates/candidate/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/candidate/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Candidate{% endblock %}

{% block body %}
    <h1>Edit Candidate</h1>

    {{ include('candidate/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_candidate_index') }}">back to list</a>

    {{ include('candidate/_delete_form.html.twig') }}
{% endblock %}

templates/candidate/index.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}Candidate index{% endblock %}

{% block body %}
<div style="height:100px"></div>
    <h1>Candidate index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Email</th>
                <th>Current Location</th>
                <th>Job Category</th>
                <th>Availability</th>
                <th>Inscription Date</th>
            </tr>
        </thead>
        <tbody>
        {% for candidate in candidates %}
            <tr>
                <td>{{ candidate.firstname }}</td>
                <td>{{ candidate.lastname }}</td>
                <td><a href="mailto:{{ candidate.user.email }}">{{ candidate.user.email }}</a></td>
                <td>{{ candidate.currentLocation }}</td>
                <td>{{ candidate.jobCategoryId ? candidate.jobCategoryId.name : '' }}</td>
                <td>{{ candidate.availability ? 'yes' : 'no' }}</td>
                <td>{{ candidate.createdAt|date('Y-m-d') }}</td>          
                <td>
                    <a href="{{ path('app_candidate_show', {'id': candidate.user.id}) }}">show</a>
                    <a href="{{ path('app_candidate_new', {'id': candidate.user.id}) }}">edit</a>
                    <form method="post" action="{{ path('app_candidate_delete', {'id': candidate.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ candidate.id) }}">
                        <button class="btn">Delete</button>
                    </form>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="23">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/candidate/show.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}Candidate{% endblock %}

{% block body %}
<div style="height:100px"></div>
    <h1>Candidate</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ candidate.id }}</td>
            </tr>
            <tr>
                <th>Firstname</th>
                <td>{{ candidate.firstname }}</td>
            </tr>
            <tr>
                <th>Lastname</th>
                <td>{{ candidate.lastname }}</td>
            </tr>
            <tr>
                <th>Gender</th>
                <td>{{ candidate.gender }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ candidate.address }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ candidate.country }}</td>
            </tr>
            <tr>
                <th>Nationality</th>
                <td>{{ candidate.nationality }}</td>
            </tr>
            <tr>
                <th>Passport</th>
                <td>{{ candidate.passport ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Passport_file</th>
                <td>{{ candidate.passportFile }}</td>
            </tr>
            <tr>
                <th>Cv</th>
                <td>{{ candidate.cv }}</td>
            </tr>
            <tr>
                <th>Profile_picture</th>
                <td>{{ candidate.profilePicture }}</td>
            </tr>
            <tr>
                <th>Current_location</th>
                <td>{{ candidate.currentLocation }}</td>
            </tr>
            <tr>
                <th>Birthdate</th>
                <td>{{ candidate.birthdate ? candidate.birthdate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Birth_location</th>
                <td>{{ candidate.birthLocation }}</td>
            </tr>
            <tr>
                <th>Availability</th>
                <td>{{ candidate.availability ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Experience</th>
                <td>{{ candidate.experience }}</td>
            </tr>
            <tr>
                <th>Short_description</th>
                <td>{{ candidate.shortDescription }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ candidate.createdAt ? candidate.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ candidate.updatedAt ? candidate.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Deleted_at</th>
                <td>{{ candidate.deletedAt ? candidate.deletedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Deleted</th>
                <td>{{ candidate.deleted ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Files</th>
                <td>{{ candidate.files }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_candidate_index') }}">back to list</a>

    <a href="{{ path('app_candidate_edit', {'id': candidate.user.id}) }}">edit</a>

    {{ include('candidate/_delete_form.html.twig') }}
{% endblock %}